a = input('type something: ')
print('the primitive type of this value is: ', type(a))
print('There are only spaces?', a.isspace())
print('Is it a number?', a.isnumeric())
print('Is it alphabetic?', a.isalpha())
print('Is it alphanumeric?'), a.isalnum()