name = str(input('Please type your name'))
print('upper = ', name.upper())
print('lower = ', name.lower())
AmountOfLetters = name.split()
print('First name contains: ', len(AmountOfLetters[0]))
print('Your full name has {} letters'.format(len(name)-name.count(' ')))
split = name.split()
print('Your first name is {} and it has {} letters'.format(split[0], len(split[0])))